# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish To Mod Sites

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'mc**'
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - 'master'
      - 'mc**'
    paths-ignore:
      - '.github/**'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle build
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew publishToModSites

      - uses: actions/upload-artifact@v3
        with:
          name: Forge
          path: forge/build/libs

      - uses: actions/upload-artifact@v3
        with:
          name: Fabric
          path: fabric/build/libs
